[2023-11-18 19:42:11,971] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_hh.load_core_dim_currency manual__2023-11-18T19:41:34.961700+00:00 [queued]>
[2023-11-18 19:42:11,999] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_hh.load_core_dim_currency manual__2023-11-18T19:41:34.961700+00:00 [queued]>
[2023-11-18 19:42:11,999] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-11-18 19:42:12,011] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2023-11-18 19:42:12,012] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-11-18 19:42:12,049] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): load_core_dim_currency> on 2023-11-18 19:41:34.961700+00:00
[2023-11-18 19:42:12,059] {standard_task_runner.py:52} INFO - Started process 13642 to run task
[2023-11-18 19:42:12,063] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_hh', 'load_core_dim_currency', 'manual__2023-11-18T19:41:34.961700+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp95y2bz3i', '--error-file', '/tmp/tmpkgkmr52l']
[2023-11-18 19:42:12,064] {standard_task_runner.py:80} INFO - Job 103: Subtask load_core_dim_currency
[2023-11-18 19:42:12,188] {task_command.py:371} INFO - Running <TaskInstance: etl_hh.load_core_dim_currency manual__2023-11-18T19:41:34.961700+00:00 [running]> on host 2e176173f0f7
[2023-11-18 19:42:12,413] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_hh
AIRFLOW_CTX_TASK_ID=load_core_dim_currency
AIRFLOW_CTX_EXECUTION_DATE=2023-11-18T19:41:34.961700+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-18T19:41:34.961700+00:00
[2023-11-18 19:42:12,439] {base.py:68} INFO - Using connection ID 'my_db_conn' for task execution.
[2023-11-18 19:42:12,474] {dbapi.py:231} INFO - Running statement: INSERT INTO core_layer.dim_experience(
                currency_id, 
                to_rub
            )
            SELECT DISTINCT
                salary_currency,
                CASE
                    WHEN salary_currency = 'RUR'
                    THEN 1
                    WHEN salary_currency = 'USD'
                    THEN 89
                    WHEN salary_currency = 'KZT'
                    THEN 0.2
                    WHEN salary_currency = 'BYR'
                    THEN 28.7
                END AS to_rub
            FROM staging_layer.vacancy, parameters: None
[2023-11-18 19:42:12,485] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "currency_id" of relation "dim_experience" does not exist
LINE 2:                 currency_id, 
                        ^

[2023-11-18 19:42:12,514] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_hh, task_id=load_core_dim_currency, execution_date=20231118T194134, start_date=20231118T194211, end_date=20231118T194212
[2023-11-18 19:42:12,543] {standard_task_runner.py:97} ERROR - Failed to execute job 103 for task load_core_dim_currency (column "currency_id" of relation "dim_experience" does not exist
LINE 2:                 currency_id, 
                        ^
; 13642)
[2023-11-18 19:42:12,597] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-18 19:42:12,702] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
